# Generated by Django 3.0.4 on 2020-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20200321_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='label',
            field=models.CharField(choices=[('探索的データ分析', '探索的データ分析'), ('前処理', '前処理'), ('特徴量エンジニアリング', '特徴量エンジニアリング'), ('モデリング', 'モデリング'), ('検証', '検証'), ('アンサンブル', 'アンサンブル'), ('その他', 'その他')], default='前処理', max_length=32),
        ),
    ]
