# Generated by Django 3.0.4 on 2020-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='slack_url',
            field=models.URLField(default=''),
        ),
    ]
